add new message for triggering thoth-repo-init
thoth-station/messaging pull request #447
Opened 2021-11-16 20:49 UTC by KPostOffice

## Related Issues and Dependencies

This will be consumed to schedule thoth-repo-init workflow

2021-11-16 20:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **kpostoffice** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmessaging).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/messaging/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kpostoffice"]} -->

2021-11-17 14:23 UTC, harshad16 requested changes
lgtm
some doubts

2021-11-17 14:23 UTC, harshad16 commented on thoth/messaging/thoth_repo_init.py
> +# Copyright(C) 2020 Kevin Postlethwait
```suggestion
# Copyright(C) 2021 Kevin Postlethwait
```

2021-11-17 14:23 UTC, harshad16 commented on thoth/messaging/thoth_repo_init.py
> +"""This is Thoth Messaging module for MissingVersionMessage."""
is this description , right?

2021-11-18 08:34 UTC, fridex approved these changes
lgtm 👍🏻 thanks!

2021-11-18 08:34 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/messaging/pull/447#pullrequestreview-809606349" title="Approved">fridex</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **kpostoffice** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmessaging).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/messaging/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kpostoffice"]} -->

2021-12-01 18:27 UTC, KPostOffice commented
/priority critical-urgent

2021-12-07 20:36 UTC, KPostOffice commented
/approve

2021-12-07 20:36 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/messaging/pull/447#pullrequestreview-809606349" title="Approved">fridex</a>*, *<a href="https://github.com/thoth-station/messaging/pull/447#issuecomment-988246440" title="Approved">KPostOffice</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmessaging).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/messaging/blob/master/OWNERS)~~ [KPostOffice]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-12-08 15:42 UTC, merged